# Generated by Django 4.0.1 on 2022-01-16 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('numero_articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.producto')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Prodcutos',
            },
        ),
    ]
