# Generated by Django 4.0.1 on 2022-01-16 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_venta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='numero_articulo',
            new_name='numeroArticulo',
        ),
    ]
